# ============================================================
#  This file is part of DataLaVista
#  build.ps1: DataLaVista build script (Windows PowerShell).
#  Author(s): Gabriel Mongefranco; Jeremy Gluskin; Shelley Boa.
#  Created: 2026-03-24
#  Last Modified: 2026-03-24
#  Summary: Generates datalavista.js, DataLaVista.html, DataLaVista-nojs.html, DataLaVista-dev.html.
#  Notes: See README file for documentation and full license information.
#  Website: https://github.com/DepressionCenter/datalavista
#
#  Copyright (c) 2026 The Regents of the University of Michigan
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#  You should have received a copy of the GNU General Public License along
#  with this program. If not, see <https://www.gnu.org/licenses/>.
#  ================================================================

$ErrorActionPreference = 'Stop'
$SRC = 'src'
$PlaceholderPattern = '(?s)<!-- DATALAVISTA_SCRIPTS_PLACEHOLDER_OPEN -->.*?<!-- DATALAVISTA_SCRIPTS_PLACEHOLDER_CLOSE -->'

# Collect JS source files in sort order
$JsFiles = Get-ChildItem "$SRC\[0-9][0-9]-*.js" | Sort-Object Name

# ── Helper: replace placeholder block in template ────────────────────────────
function Replace-Placeholder {
    param([string]$TemplatePath, [string]$Snippet, [string]$OutputPath)
    $template = [System.IO.File]::ReadAllText($TemplatePath, [System.Text.Encoding]::UTF8)
    $result   = [regex]::Replace($template, $PlaceholderPattern, [System.Text.RegularExpressions.MatchEvaluator]{ param($m) $Snippet })
    [System.IO.File]::WriteAllText($OutputPath, $result, [System.Text.Encoding]::UTF8)
}

# ── 1. Build datalavista.js ──────────────────────────────────────────────────
Write-Host 'Building datalavista.js...'
$sourceHash = (& git rev-parse --short HEAD 2>$null)
if (-not $sourceHash) { $sourceHash = 'unknown' }
$jsLicenseHeader = @"
/* ============================================================
This file is part of DataLaVista
datalavista.js: DataLaVista concatenated module - all source files bundled as an IIFE.
Author(s): Gabriel Mongefranco; Jeremy Gluskin; Shelley Boa.
Source: $sourceHash
Notes: This file is auto-generated by build.ps1. Edit src/ files, not this file.
       See README file for documentation and full license information.
Website: https://github.com/DepressionCenter/datalavista

Copyright (c) 2026 The Regents of the University of Michigan

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.
You should have received a copy of the GNU General Public License along
with this program. If not, see https://www.gnu.org/licenses/.
================================================================ */

"@
$sb = [System.Text.StringBuilder]::new()
$null = $sb.Append($jsLicenseHeader)
$null = $sb.AppendLine('(() => {')
$null = $sb.AppendLine("  'use strict';")
foreach ($f in $JsFiles) {
    $null = $sb.AppendLine("")
    $null = $sb.AppendLine("  /* === $($f.Name) === */")
    $null = $sb.Append([System.IO.File]::ReadAllText($f.FullName, [System.Text.Encoding]::UTF8))
    $null = $sb.AppendLine("")
}
$null = $sb.AppendLine("")
$null = $sb.AppendLine("})();")
$null = $sb.AppendLine("")
$null = $sb.AppendLine("// Backward-compat shim: re-expose all dlv methods as globals so")
$null = $sb.AppendLine("// onclick=""foo()"" HTML attributes continue to work.")
$null = $sb.AppendLine("if (window.dlv) {")
$null = $sb.AppendLine("  for (const [k, v] of Object.entries(window.dlv)) {")
$null = $sb.AppendLine("    if (typeof v === 'function' && !Object.prototype.hasOwnProperty.call(window, k)) {")
$null = $sb.AppendLine("      window[k] = (...a) => window.dlv[k](...a);")
$null = $sb.AppendLine("    }")
$null = $sb.AppendLine("  }")
$null = $sb.AppendLine("}")
[System.IO.File]::WriteAllText('datalavista.js', $sb.ToString(), [System.Text.Encoding]::UTF8)
$lineCount = (Get-Content 'datalavista.js').Count
Write-Host "  -> datalavista.js ($lineCount lines)"

# ── 2. Build DataLaVista-nojs.html ─────────────────────────────────────────
Write-Host 'Building DataLaVista-nojs.html...'
Replace-Placeholder "$SRC\00-full-page.html" `
    '  <script src="datalavista.js"></script>' `
    'DataLaVista-nojs.html'
Write-Host '  -> DataLaVista-nojs.html'

# ── 3. Build DataLaVista-dev.html ────────────────────────────────────────────
Write-Host 'Building DataLaVista-dev.html...'
$devTags = ($JsFiles | ForEach-Object { "  <script src=`"$SRC/$($_.Name)`"></script>" }) -join "`n"
Replace-Placeholder "$SRC\00-full-page.html" $devTags 'DataLaVista-dev.html'
Write-Host '  -> DataLaVista-dev.html'

# ── 4. Build DataLaVista.html (inline) ──────────────────────────────────────
Write-Host 'Building DataLaVista.html (inline)...'
$inlineSb = [System.Text.StringBuilder]::new()
$null = $inlineSb.AppendLine("  <script>")
foreach ($f in $JsFiles) {
    $null = $inlineSb.Append([System.IO.File]::ReadAllText($f.FullName, [System.Text.Encoding]::UTF8))
    $null = $inlineSb.AppendLine("")
}
$null = $inlineSb.Append("  </script>")
Replace-Placeholder "$SRC\00-full-page.html" $inlineSb.ToString() 'DataLaVista.html'
Write-Host '  -> DataLaVista.html'

Write-Host ''
Write-Host 'Build complete.'
