#!/usr/bin/env bash
# ============================================================
#  This file is part of DataLaVista
#  build.sh: DataLaVista build script (Linux / macOS / GitHub Actions).
#  Author(s): Gabriel Mongefranco; Jeremy Gluskin; Shelley Boa.
#  Created: 2026-03-24
#  Last Modified: 2026-03-31
#  Summary: Generates datalavista.js, DataLaVista.html, DataLaVista-nojs.html, DataLaVista-dev.html.
#  Notes: See README file for documentation and full license information.
#  Website: https://github.com/DepressionCenter/datalavista
#  
#  Copyright © 2026 The Regents of the University of Michigan
#  
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#  You should have received a copy of the GNU General Public License along
#  with this program. If not, see <https://www.gnu.org/licenses/>.
#  ================================================================ */
set -e

SRC="src"
PLACEHOLDER_OPEN="<!-- DATALAVISTA_SCRIPTS_PLACEHOLDER_OPEN -->"
PLACEHOLDER_CLOSE="<!-- DATALAVISTA_SCRIPTS_PLACEHOLDER_CLOSE -->"

# Collect JS source files in sort order (01-*.js through 15-*.js)
JS_FILES=$(ls "$SRC"/[0-9][0-9]-*.js | sort)

# ── 1. Build datalavista.js ──────────────────────────────────────────────────
echo "Building datalavista.js..."
{
  echo "/* ============================================================"
  echo "This file is part of DataLaVista"
  echo "datalavista.js: DataLaVista concatenated module — all source files bundled as an IIFE."
  echo "Author(s): Gabriel Mongefranco; Jeremy Gluskin; Shelley Boa."
  echo "Source: $(git rev-parse --short HEAD 2>/dev/null || echo 'unknown')"
  echo "Notes: This file is auto-generated by build.sh. Edit src/ files, not this file."
  echo "       See README file for documentation and full license information."
  echo "Website: https://github.com/DepressionCenter/datalavista"
  echo ""
  echo "Copyright (c) 2026 The Regents of the University of Michigan"
  echo ""
  echo "This program is free software: you can redistribute it and/or modify"
  echo "it under the terms of the GNU General Public License as published by"
  echo "the Free Software Foundation, either version 3 of the License, or (at your option) any later version."
  echo "This program is distributed in the hope that it will be useful,"
  echo "but WITHOUT ANY WARRANTY; without even the implied warranty of"
  echo "MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the"
  echo "GNU General Public License for more details."
  echo "You should have received a copy of the GNU General Public License along"
  echo "with this program. If not, see <https://www.gnu.org/licenses/>."
  echo "================================================================ */"
  echo ""
  echo "(() => {"
  echo "  'use strict';"
  for f in $JS_FILES; do
    echo ""
    echo "  /* === $(basename "$f") === */"
    cat "$f"
  done
  echo ""
  echo "})();"
  echo ""
  echo "// Backward-compat shim: re-expose all dlv methods as globals so"
  echo "// onclick=\"foo()\" HTML attributes continue to work."
  echo "if (window.dlv) {"
  echo "  for (const [k, v] of Object.entries(window.dlv)) {"
  echo "    if (typeof v === 'function' && !Object.prototype.hasOwnProperty.call(window, k)) {"
  echo "      window[k] = (...a) => window.dlv[k](...a);"
  echo "    }"
  echo "  }"
  echo "}"
} > datalavista.js
echo "  -> datalavista.js ($(wc -l < datalavista.js) lines)"

# ── Helper: replace placeholder in template using Python (portable, no sed issues) ──
replace_placeholder() {
  local template="$1"
  local replacement_file="$2"
  local output="$3"
  python - "$template" "$replacement_file" "$output" <<'PYEOF'
import sys, re
template_path, replacement_file, output_path = sys.argv[1], sys.argv[2], sys.argv[3]
template = open(template_path, encoding='utf-8').read()
replacement = open(replacement_file, encoding='utf-8').read()
result = re.sub(
    r'<!-- DATALAVISTA_SCRIPTS_PLACEHOLDER_OPEN -->.*?<!-- DATALAVISTA_SCRIPTS_PLACEHOLDER_CLOSE -->',
    lambda m: replacement,
    template,
    count=1,
    flags=re.DOTALL
)
open(output_path, 'w', encoding='utf-8').write(result)
PYEOF
}

# ── 2. Build DataLaVista-nojs.html ─────────────────────────────────────────
echo "Building DataLaVista-nojs.html..."
echo '  <script src="datalavista.js"></script>' > /tmp/dlv_snippet.txt
replace_placeholder "$SRC/00-full-page.html" /tmp/dlv_snippet.txt DataLaVista-nojs.html
echo "  -> DataLaVista-nojs.html"

# ── 3. Build DataLaVista-dev.html ────────────────────────────────────────────
echo "Building DataLaVista-dev.html..."
{
  for f in $JS_FILES; do
    echo "  <script src=\"$f\"></script>"
  done
} > /tmp/dlv_snippet.txt
replace_placeholder "$SRC/00-full-page.html" /tmp/dlv_snippet.txt DataLaVista-dev.html
echo "  -> DataLaVista-dev.html"

# ── 4. Build DataLaVista.html (inline) ──────────────────────────────────────
echo "Building DataLaVista.html (inline)..."
{
  echo "  <script>"
  for f in $JS_FILES; do
    cat "$f"
    echo ""
  done
  echo "  </script>"
} > /tmp/dlv_snippet.txt
replace_placeholder "$SRC/00-full-page.html" /tmp/dlv_snippet.txt DataLaVista.html
echo "  -> DataLaVista.html"

rm -f /tmp/dlv_snippet.txt
echo ""
echo "Build completed at $(date '+%Y-%m-%d %I:%M:%S %p')."
